version: '3.8'

services:
  php:
    build:
      context: ./php
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizza_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
